version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE= test_db
      - MYSQL_USER= root
      - MYSQL_ROOT_PASSWORD=123456
    ports:
    - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: